from .connectSwitches import connectSwitches
from .writePrefStateSwitches import writePrefStateSwitches
from .programStart import programStart
from .updateStartTime import updateStartTime
from .shutDownSwitches import shutDownSwitches
from .updateRunningStop import updateRunningStop
from .getTable import getTable
from .readFlowSensor import readFlowSensor
from .setupLogging import setupLogging
